### ISSUE TITLE
Improvement idea: Save to iCloud Drive

### ISSUE THREAD

**Issue by Pimpnase** [thatvirtualboy/SwiftUI-Bento-Box#1]
You have a wonderful app. As I'm using it on an M1 MBP with macOS (but would also be useful for iPads) I would love an option to save to iCloud Drive (or file-system). Otherwise there is no option to comfortably get the created image.

**Comment by thatvirtualboy** [comment]
Thanks for the suggestion! However as this is first and foremost an iPad app, I will not be adding macOS specific actions or capability outside of that platform. As it stands, Bento|Craft for iPad uses the system default `ShareLink` which does support saving to iCloud Drive (via 'Save to Files'). Therefore I'll be closing this as will not fix.
