### ISSUE TITLE
Improvement idea: Transparent background

### ISSUE THREAD

**Issue by Pimpnase** [thatvirtualboy/SwiftUI-Bento-Box#3]
You have a wonderful app. As I'm using it on an M1 MBP with macOS (but would also be useful for iPads) I would love an option to save the image with a transparent background (or a different color background). I want to put the Bento-image onto a presentation, which has a color-gradient in the background. As currently it's always "white", this looks weird. Also it would be nice to select a different/individual background-color for the Bento-image (or leave it transparent all the time).

**Comment by thatvirtualboy** [comment]
This is a neat idea. I'll include a method for custom background colors. Transparent won't be an option unfortunately since the exported image is simply a screen capture of what's presented in the view.
