### ISSUE TITLE
Distorted icons

### ISSUE THREAD

**Issue by Pimpnase** [thatvirtualboy/SwiftUI-Bento-Box#5]
**IS**
- Some icons are displayed distorted and are stretched vertically in some Bento-elements

**SHOULD**
- Icons should always be resized within the same ratio for height/width in all Bento-elements

**Reproduce**
- Start Bento|Craft-app
- Create a new Bento-Board with size "Max Craft"
- Click on the "For Frodo"-element
- Click on the icon in the edit-element
- Select category "Accessibility"
- Select 1st icon "man ... women" (see attached screenshot)

![Bildschirmfoto 2023-10-26 um 16 29 28](https://github.com/thatvirtualboy/SwiftUI-Bento-Box/assets/870589/f6b4a583-b032-448d-9711-b8cd928fcf84)
![Bildschirmfoto 2023-10-26 um 16 29 32](https://github.com/thatvirtualboy/SwiftUI-Bento-Box/assets/870589/b4e71687-f39a-47bf-9839-05191701492f)

**Comment by thatvirtualboy** [comment]
The fix has been implemented and will be included in the next App Store release. Thanks for reporting!
