### ISSUE TITLE
Sheets not appearing sometimes

### ISSUE THREAD

**Issue by AndreasInk** [thatvirtualboy/SwiftUI-Bento-Box#6]
Love the concept of the app! One issue I'm running into on iPadOS 17.0.3 is that sheets are not properly displaying sometimes. Happy to give more info if needed!

**Comment by thatvirtualboy** [comment]
Hi! Thanks for mentioning this! Any chance you can update to 17.1+

 This is a known issue with 17.0

**Comment by AndreasInk** [comment]
I'll update! Thanks again, great app!
