### ISSUE TITLE
Changing app icon not supported on Mac

### ISSUE THREAD

**Issue by infinitepower18** [thatvirtualboy/SwiftUI-Bento-Box#7]
macOS doesn't support the ability to change the app icon, but the option remains present when run on a Mac.

![image](https://github.com/thatvirtualboy/SwiftUI-Bento-Box/assets/44692189/4e343a1f-7a3c-4241-bc4b-22176e9e2b35)

You can fix this by doing a `ProcessInfo.processInfo.isiOSAppOnMac` check and if true, don't show the option.

**Comment by thatvirtualboy** [comment]
Fixed in next update. Thanks!
